### ISSUE TITLE
ONNXRuntimeError : 6 : RUNTIME_EXCEPTION : Exception during initialization:

### ISSUE THREAD

**Issue by lord-lethris** [Gourieff/comfyui-reactor-node#319]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

I'm using ZLUDA (switched from DirectML - honestly its miles better), I don't know much about the ins and outs, but I _think_ it kinda emulates CUDA on AMD GPUs, and it works really well...

I've had issues in the past with ReActor not working at all with DirectML and there was a code hack to get it to work.  And it was kindly eventually added to to the main trunk.  Now I'm having the same issue with ZLUDA.

As a suggestion, can we have the option on the node to force use CPU only?

As a note - ReActor is the only node that doesn't seem to work when running ZLUDA, so I guess it doesn't pull requests for CUDA from the same code and/or routines that all the other nodes use.? (_which isn't a moan btw_)

Error is:

```
[ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDNN failure 4: CUDNN_STATUS_INTERNAL_ERROR ; GPU=0 ; hostname=DESKTOP-GH34TUD ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=178 ; expr=cudnnSetStream(cudnn_handle_, stream);

File "D:\apps\SD-WebUI\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "D:\apps\SD-WebUI\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "D:\apps\SD-WebUI\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "D:\apps\SD-WebUI\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 334, in execute
script.process(
File "E:\ASSETS\AI-TOOLS\COMFY-DATA\custom_nodes\comfyui-reactor-node\scripts\reactor_faceswap.py", line 91, in process
result = swap_face(
File "E:\ASSETS\AI-TOOLS\COMFY-DATA\custom_nodes\comfyui-reactor-node\scripts\reactor_swapper.py", line 230, in swap_face
source_faces = analyze_faces(source_img)
File "E:\ASSETS\AI-TOOLS\COMFY-DATA\custom_nodes\comfyui-reactor-node\scripts\reactor_swapper.py", line 147, in analyze_faces
face_analyser = getAnalysisModel(det_size)
File "E:\ASSETS\AI-TOOLS\COMFY-DATA\custom_nodes\comfyui-reactor-node\scripts\reactor_swapper.py", line 77, in getAnalysisModel
ANALYSIS_MODEL = insightface.app.FaceAnalysis(
File "E:\ASSETS\AI-TOOLS\COMFY-DATA\custom_nodes\comfyui-reactor-node\reactor_patcher.py", line 48, in patched_faceanalysis_init
model = model_zoo.get_model(onnx_file, **kwargs)
File "D:\apps\Python\Python310\lib\site-packages\insightface\model_zoo\model_zoo.py", line 96, in get_model
model = router.get_model(providers=providers, provider_options=provider_options)
File "E:\ASSETS\AI-TOOLS\COMFY-DATA\custom_nodes\comfyui-reactor-node\reactor_patcher.py", line 21, in patched_get_model
session = PickableInferenceSession(self.onnx_file, **kwargs)
File "D:\apps\Python\Python310\lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
super().__init__(model_path, **kwargs)
File "D:\apps\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
self._create_inference_session(providers, provider_options, disabled_optimizers)
File "D:\apps\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 483, in _create_inference_session
sess.initialize_session(providers, provider_options, disabled_optimizers)
```

### Steps to reproduce the problem

Just created a simple workflow

![workflow (21)](https://github.com/Gourieff/comfyui-reactor-node/assets/1736720/110f55e3-4365-49e6-a9bd-3d9ec3cfae3c)

### Sysinfo

OS - Windows 11
Browser - Edge, also tried Opera GX.
GPU - Radeon RX 6800 XT

Nodes Running (_But not necessarily on the workflow_):

brightness_contrast_ally
clip_text_encode_split
gaussian_blur_ally
histogram_equalization
ComfyUi-NoodleWebcam
sharpness_ally
DeepCash
ComfyUI-VideoHelperSuite
saturation_ally
imageflip_ally
ComfyUI_IPAdapter_plus
fcSuite
efficiency-nodes-comfyui
rembg-comfyui-node
ksampler_sdxl
SDXLAspectRatio
Pseudo_HDR_ally
websocket_image_save
conditioning_sizing_for_SDXL
ComfyUI-Styles_CSV_Loader
CLIPTextFromTemplateEncode
ComfyUI-sampler-lcm-alternative
ComfyUI-StableDiffusion3-API
sdxl_prompt_styler
ComfyUI_Noise
comfyui-optical-flow
ComfyUI_ADV_CLIP_emb
ComfyUI-Gtsuya-Nodes
comfyui_controlnet_aux
comfyui-tooling-nodes
pose-generator-comfyui-node
comfyui-portrait-master
ComfyUI_SimpleMath
ComfyUI_Cutoff
ComfyUI_toyxyz_test_nodes
ComfyUI_JPS-Nodes
ComfyUI-post-processing-nodes
ComfyUI_TiledIPAdapter
ComfyUI_essentials
comfyui-ultralytics-yolo
comfy_clip_blip_node
ComfyUI_TiledKSampler
ComfyUi_NNLatentUpscale
ComfyUI-OpenPose-Editor
SD-Advanced-Noise
ComfyUI-WD14-Tagger
ComfyUI-TGu-utils
ComfyUI_experiments
comfy-plasma
ComfyUI-QualityOfLifeSuit_Omar92
ComfyQR-scanning-nodes
ComfyUI_FizzNodes
comfyui-inpaint-nodes
ComfyMath
ComfyUI_NestedNodeBuilder
comfyui-animatediff
images-grid-comfy-plugin
ComfyUI_Load_Image_With_Metadata
failfast-comfyui-extensions
ComfyUI_UltimateSDUpscale
ComfyUI-Advanced-ControlNet
ComfyQR
tri3d-comfyui-nodes
ComfyUI-Marigold
ComfyUI-AnimateDiff-Evolved
rgthree-comfy
ComfyUI-NegiTools
ComfyUI_Comfyroll_CustomNodes
comfy_mtb
comfyui-prompt-control
comfyui-prompt-reader-node
facerestore_cf
comfyui-reactor-node
ComfyUI_tinyterraNodes
ComfyUI-Hangover-Moondream
SeargeSDXL
Comfyui_segformer_b2_clothes
ComfyUI-Frame-Interpolation
ComfyUI-KJNodes
comfyui-dynamicprompts
ComfyUI-APISR
clipseg
ComfyUI-Custom-Scripts
ComfyUI-Manager
ComfyUI-Inspire-Pack
ComfyUI-Allor
Jovimetrix
ComfyUI-Portrait-Maker
was-node-suite-comfyui
comfyui-mixlab-nodes
ComfyUI-Crystools
ComfyUI-Impact-Pack
ComfyUI_Custom_Nodes_AlekPet
ComfyUI-DiffusersStableCascade
comfyui-art-venture

### Relevant console log

```Shell
got prompt
[rgthree] Using rgthree's optimized recursive execution.
100%|█████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.59it/s]
[ReActor] 17:00:35 - STATUS - Working: source face index [0], target face index [0]
[ReActor] 17:00:35 - STATUS - Analyzing Source Image...
2024-05-22 17:00:35.8014171 [E:onnxruntime:, inference_session.cc:1981 onnxruntime::InferenceSession::Initialize::<lambda_b88fb06a047eb3fba81e04c489d52b7d>::operator ()] Exception during initialization: D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDNN failure 4: CUDNN_STATUS_INTERNAL_ERROR ; GPU=0 ; hostname=DESKTOP-GH34TUD ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=178 ; expr=cudnnSetStream(cudnn_handle_, stream);


!!! Exception during processing!!! [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDNN failure 4: CUDNN_STATUS_INTERNAL_ERROR ; GPU=0 ; hostname=DESKTOP-GH34TUD ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=178 ; expr=cudnnSetStream(cudnn_handle_, stream);


Traceback (most recent call last):
  File "D:\apps\SD-WebUI\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\apps\SD-WebUI\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\apps\SD-WebUI\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\apps\SD-WebUI\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 334, in execute
    script.process(
  File "E:\ASSETS\AI-TOOLS\COMFY-DATA\custom_nodes\comfyui-reactor-node\scripts\reactor_faceswap.py", line 91, in process
    result = swap_face(
  File "E:\ASSETS\AI-TOOLS\COMFY-DATA\custom_nodes\comfyui-reactor-node\scripts\reactor_swapper.py", line 230, in swap_face
    source_faces = analyze_faces(source_img)
  File "E:\ASSETS\AI-TOOLS\COMFY-DATA\custom_nodes\comfyui-reactor-node\scripts\reactor_swapper.py", line 147, in analyze_faces
    face_analyser = getAnalysisModel(det_size)
  File "E:\ASSETS\AI-TOOLS\COMFY-DATA\custom_nodes\comfyui-reactor-node\scripts\reactor_swapper.py", line 77, in getAnalysisModel
    ANALYSIS_MODEL = insightface.app.FaceAnalysis(
  File "E:\ASSETS\AI-TOOLS\COMFY-DATA\custom_nodes\comfyui-reactor-node\reactor_patcher.py", line 48, in patched_faceanalysis_init
    model = model_zoo.get_model(onnx_file, **kwargs)
  File "D:\apps\Python\Python310\lib\site-packages\insightface\model_zoo\model_zoo.py", line 96, in get_model
    model = router.get_model(providers=providers, provider_options=provider_options)
  File "E:\ASSETS\AI-TOOLS\COMFY-DATA\custom_nodes\comfyui-reactor-node\reactor_patcher.py", line 21, in patched_get_model
    session = PickableInferenceSession(self.onnx_file, **kwargs)
  File "D:\apps\Python\Python310\lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
    super().__init__(model_path, **kwargs)
  File "D:\apps\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "D:\apps\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 483, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDNN failure 4: CUDNN_STATUS_INTERNAL_ERROR ; GPU=0 ; hostname=DESKTOP-GH34TUD ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=178 ; expr=cudnnSetStream(cudnn_handle_, stream);



Prompt executed in 5.27 seconds
```

**Comment by Michael2Miller** [comment]
I faced same problem and i found the solution bro

!apt-get update
!apt-get install cuda-toolkit-11-8
import os
os.environ["LD_LIBRARY_PATH"] += ":" + "/usr/local/cuda-11/lib64"
os.environ["LD_LIBRARY_PATH"] += ":" + "/usr/local/cuda-11.8/lib64"

Then install
!pip install onnxruntime-gpu==1.17.0

Install it and everything gonna be alright.. you will never see that problem again 

It's not a bug in programming reactor all what you need is missed files which will be installed by the first command that i sent to you
... Have a nice day🙃

**Comment by flynet** [comment]
I don't have even path like D:\a\_work\1\s\ ... from where is this ?

**Comment by lord-lethris** [comment]
> I faced same problem and i found the solution bro
> 
> !apt-get update !apt-get install cuda-toolkit-11-8 import os os.environ["LD_LIBRARY_PATH"] += ":" + "/usr/local/cuda-11/lib64" os.environ["LD_LIBRARY_PATH"] += ":" + "/usr/local/cuda-11.8/lib64"
> 
> Then install !pip install onnxruntime-gpu==1.17.0
> 
> Install it and everything gonna be alright.. you will never see that problem again
> 
> It's not a bug in programming reactor all what you need is missed files which will be installed by the first command that i sent to you ... Have a nice day🙃

I'm running on widows, not Linux - but i'll see if I can re-create this fix... somehow...

**Comment by flynet** [comment]
pip uninstall onnxruntime
Installed CUDA, Cdnn ( in my case Cuda 12. ) .. and installed proper version of onnxruntime 
according to link to documentation in error message
pip install onnxruntime==1.18.0
error gone

**Comment by Gourieff** [comment]
Default CUDA version for ORT-GPU is still 11.8 according to the official documentation:
https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements

And if you need manually reinstall ORT-GPU to make it work with CUDA 12 just follow the instructions from here:
https://onnxruntime.ai/docs/install/#install-onnx-runtime-gpu-cuda-12x

**Comment by lord-lethris** [comment]
Ok, so... onnxruntime 1.18.0 fixed the issue... HOWEVER it causes ComfyUI to crash the entire PC after 8 renders.
So I've rolled back to onnxruntime 1.17.0

**Comment by Michael2Miller** [comment]
Me too I am running on Windows on comfy ui the default cuda version is 12.2 but even though after installing cuda 11.8 as I mentioned above everything became all right I didn't face any problem again with onnxruntime gpu
But ... 
The only problem that I'm still facing is with the crashing because the actor is relying on RAM more than GPU and vram 
I tried to install that Ram test but I received the a failure while trying to install it from The comfy manager
Also I'm still facing the crash when I try to use a high quality video which has over then 350 Frames because of how usage of RAM
I wish if you can add an option to choose whether we want a fast or slow processing
This would save those who has on the 29 GB or less same as in my situation
Or maybe you can put two notes one is fast reactor and another one which is not fast same as old days,,, also if you can add an option to add the mask for example ClipSeg to write negative prompts for the reactor to avoid it while face swapping..
I know a lot of requests I asked for I'm sorry for that but all what I want is for the reactor to be the best in all situations without facing problems while using it

**Comment by xszzn70** [comment]
pip install onnxruntime==1.18.0 运行代码 以修复 comfyui-reactor-node 错误问题 ZLUDA正常转译

**Comment by ManuLinares** [comment]
pip uninstall onnxruntime onnxruntime-gpu
pip install onnxruntime==1.18.0

This fixed it for me, i don't know what I'm doing.

**Comment by Amit30swgoh** [comment]
> ```shell
> 6 : RUNTIME_EXCEPTION : Exception during initialization: D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:121 onnxruntime::CudaCall D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:114 onnxruntime::CudaCall CUDNN failure 4: CUDNN_STATUS_INTERNAL_ERROR ; GPU=0 ; hostname=DESKTOP-GH34TUD ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\cuda_execution_provider.cc ; line=178 ; expr=cudnnSetStream(cudnn_handle_, stream);
> 
> 
> Traceback (most recent call last):
>   File "D:\apps\SD-WebUI\ComfyUI\execution.py", line 151, in recursive_execute
>     output_data
> ```

is it slow since no usage of Vram  only cpu?

**Comment by Kazakiri220** [comment]
> pip uninstall onnxruntime onnxruntime-gpu pip install onnxruntime==1.18.0
> 
> This fixed it for me, i don't know what I'm doing.

You replaced onnxruntime-gpu with onnxruntime, which runs in CPU instead of GPU. And so the "CUDA not functioning" problem is bypassed. This shall work as per OP suggested "can we have the option on the node to force use CPU only?".

**Comment by 0utsider0** [comment]
D:\ComfyUI_windows_portable>C:\Users\Ivan\miniconda3\python.exe -m pip uninstall onnxruntime onnxruntime-gpu pip install onnxruntime==1.18.0
WARNING: Skipping onnxruntime as it is not installed.
Found existing installation: onnxruntime-gpu 1.18.1
Uninstalling onnxruntime-gpu-1.18.1:
  Would remove:
    c:\users\ivan\miniconda3\lib\site-packages\onnxruntime\*
    c:\users\ivan\miniconda3\lib\site-packages\onnxruntime_gpu-1.18.1.dist-info\*
    c:\users\ivan\miniconda3\scripts\onnxruntime_test.exe
Proceed (Y/n)?

skipping onnxruntime as its not installed
found existing installation-

wtf is this? can anyone help me with it? this node bring so many problems man

**Comment by tevauesilesi** [comment]
@0utsider0 Your ComfyUI_windows_portable has its own virtual python environment then you should update there. You, on the other hand, updated python on your C drive
