### ISSUE TITLE
Stopped working out of the blue after restart-I didn't make any updates

### ISSUE THREAD

**Issue by ckao10301** [Gourieff/comfyui-reactor-node#502]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/comfyui-reactor-node/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Have the same issue on 2 separate pcs. Restarted comfyui and now reactor doesn't work.

2024-12-17 08:25:50.737941595 [E:onnxruntime:Default, cuda_call.cc:123 CudaCall] CUDNN failure 1002: CUDNN_STATUS_SUBLIBRARY_VERSION_MISMATCH ; GPU=0 ; hostname=Super ; file=/onnxruntime_src/onnxruntime/core/providers/cuda/cudnn_common.cc ; line=31 ; expr=cudnnCreateTensorDescriptor(&tensor_); 
2024-12-17 08:25:50.737982006 [E:onnxruntime:, sequential_executor.cc:516 ExecuteKernel] Non-zero status code returned while running Conv node. Name:'Conv_0' Status Message: CUDNN failure 1002: CUDNN_STATUS_SUBLIBRARY_VERSION_MISMATCH ; GPU=0 ; hostname=Super ; file=/onnxruntime_src/onnxruntime/core/providers/cuda/cudnn_common.cc ; line=31 ; expr=cudnnCreateTensorDescriptor(&tensor_); 
!!! Exception during processing!!! [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Conv node. Name:'Conv_0' Status Message: CUDNN failure 1002: CUDNN_STATUS_SUBLIBRARY_VERSION_MISMATCH ; GPU=0 ; hostname=Super ; file=/onnxruntime_src/onnxruntime/core/providers/cuda/cudnn_common.cc ; line=31 ; expr=cudnnCreateTensorDescriptor(&tensor_); 
Traceback (most recent call last):
  File "/home/ckao1030/Desktop/ComfyUI2/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ckao1030/Desktop/ComfyUI2/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ckao1030/Desktop/ComfyUI2/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ckao1030/Desktop/ComfyUI2/custom_nodes/comfyui-reactor-node/nodes.py", line 353, in execute
    script.process(
  File "/home/ckao1030/Desktop/ComfyUI2/custom_nodes/comfyui-reactor-node/scripts/reactor_faceswap.py", line 101, in process
    result = swap_face(
             ^^^^^^^^^^
  File "/home/ckao1030/Desktop/ComfyUI2/custom_nodes/comfyui-reactor-node/scripts/reactor_swapper.py", line 275, in swap_face
    source_faces = analyze_faces(source_img)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ckao1030/Desktop/ComfyUI2/custom_nodes/comfyui-reactor-node/scripts/reactor_swapper.py", line 181, in analyze_faces
    faces = face_analyser.get(img_data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ckao1030/Desktop/ComfyUI2/venv/lib/python3.12/site-packages/insightface/app/face_analysis.py", line 59, in get
    bboxes, kpss = self.det_model.detect(img,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ckao1030/Desktop/ComfyUI2/venv/lib/python3.12/site-packages/insightface/model_zoo/retinaface.py", line 224, in detect
    scores_list, bboxes_list, kpss_list = self.forward(det_img, self.det_thresh)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ckao1030/Desktop/ComfyUI2/venv/lib/python3.12/site-packages/insightface/model_zoo/retinaface.py", line 152, in forward
    net_outs = self.session.run(self.output_names, {self.input_name : blob})
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ckao1030/Desktop/ComfyUI2/venv/lib/python3.12/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 266, in run
    return self._sess.run(output_names, input_feed, run_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Conv node. Name:'Conv_0' Status Message: CUDNN failure 1002: CUDNN_STATUS_SUBLIBRARY_VERSION_MISMATCH ; GPU=0 ; hostname=Super ; file=/onnxruntime_src/onnxruntime/core/providers/cuda/cudnn_common.cc ; line=31 ; expr=cudnnCreateTensorDescriptor(&tensor_); 

### Steps to reproduce the problem

Your workflow

### Sysinfo

na

### Relevant console log

```Shell
see above
```

**Comment by jutochoppa** [comment]
Dude this exact thing happened to me. i reinstalled everything, restarted and then it stopped.

**Comment by jutochoppa** [comment]
i just uninstalled onnyxruntime and reinstalled and it works for me 
pip uninstall onnxruntime
pip install onnxruntime
